version: "3.7"
services:
  ddns-updater:
    build: .
    container_name: ddns-updater
    network_mode: bridge
    hostname: dynDns
    ports:
      - "0.0.0.0:8450:8000"
    volumes:
      - /home/dei/ddnsData:/updater/data
    environment:
      - CONFIG=
      - PERIOD=5m
      - UPDATE_COOLDOWN_PERIOD=5m
      - IP_METHOD=cycle
      - IPV4_METHOD=cycle
      - IPV6_METHOD=cycle
      - HTTP_TIMEOUT=10s

      # Web UI
      - LISTENING_PORT=8000
      - ROOT_URL=/

      # Backup
      - BACKUP_PERIOD=0 # 0 to disable
      - BACKUP_DIRECTORY=/updater/data

      # Other
      - LOG_LEVEL=info
      - LOG_CALLER=hidden
      - GOTIFY_URL=
      - GOTIFY_TOKEN=
    restart: always
